### PR TITLE
Fix for OSX breaking fix

### PR DESCRIPTION
**Pull request by SteveQUT**
Fix for #15

### CODE REVIEW

**Comment by SteveQUT** [comment]
@Tobias-Fischer can you confirm if this works on OSX?

**Comment by Tobias-Fischer** [comment]
I don't think it does .. these errors are coming back:
```
/dev/fd/63: line 73: read: 0.1: invalid timeout specification
```

**Comment by Tobias-Fischer** [comment]
But I am not 100% sure that I'm running the right version - I hate the "auto-update" "feature". Instead of assuming that people don't know how to run `git pull`, can we just issue a warning if we detect that it's not the last version running and that people should upgrade?

**Comment by SteveQUT** [comment]
So @btalb correct me if I'm wrong the way this works is there is a single light file in the qcr tools that has a list of all these tools. This then pulls files as needed, runs script and no changes are made to the system to use the "tools". This workflow could be changed. This is more of an issue when trying to develop for it as these types of issues mean the user has zero oversight of what they are actually running.

**Comment by btalb** [comment]
Yeah that's a correct summary of current workflow.

This definitely needs a re-think as scope has grown / changed since this was last touched:
- QCR tool is planned to run on robots; current approach unnecessarily requires Internet to do anything
- Developer / tweaking experience is tedious as you've both pointed out (you can just call `use_template` directly to get around it... but that still doesn't make it good... :stuck_out_tongue: )

What I propose:
- we wind all the "cuteness" back here:
    - essentially remove `qcr_templates` script, & rename `use_template` to `qcr_templates`
    - this will work as any other bit of software, you clone it, add a symlink of the new `qcr_templates` to your path if you want it to work like it currently does
    - no hidden auto-updating stuff, you want to update it you pull
- when we get around to getting [qcr/tools](https://github.com/qcr/tools) into shape:
    - the `qcr` script there has the cuteness of "paste this in your path and get access to all of our tools"
    - keep what it does in the background as much more transparent (clone the repo to tmp disk storage, tell the user where that is, print message when out of date as Tobi suggested rather than auto-updating)
    - that way the tools will work when offline aswell
    
Let me know if this addresses both your concerns.

As for the issue here:
- from looking at both man pages I can't see why the current version would cause an error that didn't exist before
- can have a play at some point to see if there's a workaround
- worst case, is it insulting to require GNU sed @Tobias-Fischer? (is install-able on mac)

**Comment by Tobias-Fischer** [comment]
Just on the point of GNU-sed: Why don't we use a simple `if [[ $OSTYPE == 'darwin'* ]]; then ...`? Otherwise we run into the risk that the system sed is called instead of the GNU-sed, and we will have to add a check for the OS anyhow if we want to catch osx?

**Comment by btalb** [comment]
Happy to make that change, makes more sense (GNU sed requirement would've been an absolute last resort).

Can you confirm that current master works on Mac with no inputs, and doesn't produce the errors in #16 ?

**Comment by Tobias-Fischer** [comment]
Actually the error above comes from an outdated bash version (3.x is shipped by default). With a newer bash (thanks to conda/mamba), it runs fine. Not sure if it's worth including a check for bash >= 5?

The sed command in master works as expected, but the one here in develop does not work.

**Comment by btalb** [comment]
Will sort this on `develop` branch as I address other issues.

**Comment by btalb** [comment]
All requested changes should now be live on master.

**Pull request closed without merging**
